spring:
  application:
    name: backend-base
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
  jpa:
    open-in-view: false
  main:
    allow-bean-definition-overriding: true

config:
  master-ulid: 00000000000000000000000000
  encrypt:
    secretKey: ${ENCRYPT_SECRET_KEY:TheSecretKeyLengthMustBe32Byte..}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
